controller_list:
  - name: fake_move_arm_controller
    type: $(arg execution_type)
    joints:
      - iiwa_joint_1
      - iiwa_joint_2
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7
  - name: fake_move_gripper_controller
    type: $(arg execution_type)
    joints:
      - palm_finger_1_joint
      - finger_1_joint_1
      - finger_1_joint_2
      - finger_1_joint_3
      - palm_finger_2_joint
      - finger_2_joint_1
      - finger_2_joint_2
      - finger_2_joint_3
      - finger_middle_joint_1
      - finger_middle_joint_2
      - finger_middle_joint_3
initial:  # Define initial robot poses.
#  - group: move_arm
#    pose: home

  []